In [3]:
import numpy as np
from scipy.sparse import csr_matrix

In [2]:
a = [[1, 0, 0, 0],
     [0, 0, 1, 2],
     [12, 0, 0, 1],
     [0, 0, 1, 0]]
a = np.array(a)

In [14]:
b = [[2,3,4,0],
     [0, 0,0,0],
    [0,0,0,0],
    [0,0,0,1]]
b = np.array(b)

In [4]:
S = csr_matrix(a)

In [10]:
S.data

array([ 1,  1,  2, 12,  1,  1])

In [11]:
S.indices

array([0, 2, 3, 0, 3, 2], dtype=int32)

In [12]:
S.indptr

array([0, 1, 3, 5, 6], dtype=int32)

In [15]:
T = csr_matrix(b)