In [2]:
import torch
from torch import nn

In [3]:
import itertools
from collections import Counter

In [4]:
import numpy as np

In [12]:
emb_size = 1000
emb_dim = 10
embedding = nn.Embedding(emb_size, emb_dim)
sig = nn.Sigmoid()

In [28]:
emb_1 = embedding(torch.tensor([12, 2]))
emb_2 = embedding(torch.tensor([43, 32]))

In [29]:
emb_1

tensor([[ 0.7976,  0.5950, -1.2008,  0.1782, -0.1646, -0.3091,  1.3601, -1.1299,
         -1.8383,  0.3505],
        [ 0.0983,  0.6216,  1.2589,  1.7158,  0.7322, -0.0544, -1.1300,  0.7759,
         -0.3346, -1.5656]], grad_fn=<EmbeddingBackward0>)

In [30]:
emb_2

tensor([[ 1.2093e+00,  1.7658e+00, -1.5136e-01,  5.7025e-01, -6.0432e-01,
          1.0720e+00, -1.3632e+00,  4.4260e-01, -1.0252e+00,  3.1624e-01],
        [ 1.0852e+00,  3.6491e-01,  3.6029e-01,  3.2068e-01, -1.6258e+00,
          9.2224e-01, -2.0003e-01,  6.4078e-01,  9.4780e-04, -8.4548e-01]],
       grad_fn=<EmbeddingBackward0>)

In [39]:
torch.sum(emb_1*emb_2, dim = 1, dtype = torch.float)

tensor([1.7082, 2.1433], grad_fn=<SumBackward1>)

In [31]:
emb_1*emb_2

tensor([[ 9.6455e-01,  1.0507e+00,  1.8176e-01,  1.0163e-01,  9.9473e-02,
         -3.3134e-01, -1.8540e+00, -5.0009e-01,  1.8847e+00,  1.1083e-01],
        [ 1.0666e-01,  2.2683e-01,  4.5356e-01,  5.5023e-01, -1.1903e+00,
         -5.0173e-02,  2.2602e-01,  4.9715e-01, -3.1715e-04,  1.3237e+00]],
       grad_fn=<MulBackward0>)

In [37]:
np.sum([ 9.6455e-01,  1.0507e+00,  1.8176e-01,  1.0163e-01,  9.9473e-02,
         -3.3134e-01, -1.8540e+00, -5.0009e-01,  1.8847e+00,  1.1083e-01])

1.7082129999999998

In [45]:
list(itertools.chain.from_iterable([[1,1,1], [21,5,7,8]]))

[1, 1, 1, 21, 5, 7, 8]

In [43]:
Counter([1,1,1,1,1,3,4,23,4,2,4,2,4,5,6,6,6,6,6])

Counter({1: 5, 3: 1, 4: 4, 23: 1, 2: 2, 5: 1, 6: 5})

In [17]:
d = {1:'a', 2:'b', 3:'c'}
arr = np.array([1,2,3,1,1,1,2,3]*1000)

In [18]:
%%timeit
np.array([d[a] for a in arr])    

3.11 ms ± 25.9 µs per loop (mean ± std. dev. of 7 runs, 100 loops each)


In [19]:
arr = np.array([1,2,3,1,1,1,2,3]*1000)

In [20]:
%%timeit
np.vectorize(d.get)(arr)

1.43 ms ± 12.4 µs per loop (mean ± std. dev. of 7 runs, 1,000 loops each)


In [22]:
arr = np.array(list(d.items()))

In [24]:
{k: v for k, v in arr.tolist()}

{'1': 'a', '2': 'b', '3': 'c'}

In [14]:
word_freq = {1: 12, 2: 3, 3:7, 4: 2, 5 : 43}
size = 10
word_freq = np.array(list(word_freq.items()), dtype = np.float)

/tmp/ipykernel_13900/2676925704.py:3: DeprecationWarning: `np.float` is a deprecated alias for the builtin `float`. To silence this warning, use `float` by itself. Doing this will not modify any behavior and is safe. If you specifically wanted the numpy scalar type, use `np.float64` here.
Deprecated in NumPy 1.20; for more details and guidance: https://numpy.org/devdocs/release/1.20.0-notes.html#deprecations
  word_freq = np.array(list(word_freq.items()), dtype = np.float)


In [15]:
power = 0.75
word_freq[:, 1] = word_freq[:, 1] ** power

In [16]:
word_freq

array([[ 1.        ,  6.44741959],
       [ 2.        ,  2.27950706],
       [ 3.        ,  4.30351707],
       [ 4.        ,  1.68179283],
       [ 5.        , 16.79195809]])

In [17]:
word_freq_sum = word_freq[:, 1].sum()
word_freq[:, 1] = word_freq[:, 1]/word_freq_sum
word_freq

array([[1.        , 0.20465273],
       [2.        , 0.07235567],
       [3.        , 0.1366014 ],
       [4.        , 0.05338314],
       [5.        , 0.53300706]])

In [18]:
word_freq[:, 1] = np.round(word_freq[:, 1] * size)
word_freq

array([[1., 2.],
       [2., 1.],
       [3., 1.],
       [4., 1.],
       [5., 5.]])

In [19]:
word_freq = word_freq.astype(int).tolist()
word_freq

[[1, 2], [2, 1], [3, 1], [4, 1], [5, 5]]

In [20]:
sample_table = [[tup[0]]*tup[1] for tup in word_freq]

In [21]:
sample_table

[[1, 1], [2], [3], [4], [5, 5, 5, 5, 5]]

In [22]:
import itertools

In [23]:
sample_table = np.array(list(itertools.chain.from_iterable(sample_table)))
sample_table

array([1, 1, 2, 3, 4, 5, 5, 5, 5, 5])

In [24]:
np.random.shuffle(sample_table)

In [25]:
sample_table

array([5, 5, 5, 5, 4, 1, 1, 5, 3, 2])

In [1]:
import numpy as np

In [6]:
ls = []
a = np.vstack(([[1,2], [2,3]], [[2,3], [9,8]]))
ls.append(a)
b = np.vstack(([[1,2], [2,3]], [[2,3], [9,8]]))
ls.append(b)
ls

[array([[1, 2],
        [2, 3],
        [2, 3],
        [9, 8]]),
 array([[1, 2],
        [2, 3],
        [2, 3],
        [9, 8]])]

In [7]:
np.vstack(ls)

array([[1, 2],
       [2, 3],
       [2, 3],
       [9, 8],
       [1, 2],
       [2, 3],
       [2, 3],
       [9, 8]])

In [ ]:
# neg_table_test
TABLE_SIZE = 1e7
VOCAB_SIZE = 4e5
word_freq = {i:np.random.randint(low = 0, high = 1000) for i in range(int(VOCAB_SIZE))}

power = 0.75
# Convert to array 
word_freq = np.array(list(word_freq.items()), dtype = np.float)

# adjust the power
word_freq[:, 1] = word_freq[:, 1] ** power

# Get probabilities
word_freq_sum = word_freq[:, 1].sum()
word_freq[:, 1] = word_freq[:, 1] / word_freq_sum

# Multiply probabilities by sample table size
word_freq[:, 1] = np.round(word_freq[:, 1] * TABLE_SIZE)

In [ ]:
# neg_table_test
TABLE_SIZE = 1e7
VOCAB_SIZE = 4e5
word_freq = {i:np.random.randint(low = 0, high = 1000) for i in range(int(VOCAB_SIZE))}

power = 0.75
# Convert to array 
word_freq = np.array(list(word_freq.items()), dtype = np.float)

# adjust the power
word_freq[:, 1] = word_freq[:, 1] ** power

# Get probabilities
word_freq_sum = word_freq[:, 1].sum()
word_freq[:, 1] = word_freq[:, 1] / word_freq_sum

# Multiply probabilities by sample table size
word_freq[:, 1] = np.round(word_freq[:, 1] * TABLE_SIZE)

In [ ]:
np.sum(word_freq, axis = 0)

array([7.999980e+10, 9.999614e+06])

In [ ]:
# Convert to int 
word_freq = word_freq.astype(int).tolist()


In [ ]:
word_freq[:10]

[[0, 40],
 [1, 15],
 [2, 36],
 [3, 40],
 [4, 19],
 [5, 23],
 [6, 13],
 [7, 31],
 [8, 18],
 [9, 23]]

In [ ]:

# # create the sample table
sample_table = [[tup[0]]*tup[1] for tup in tqdm(word_freq)] # repeating the index (wrod_id) by proportion of their frequency (more frequent words are more probable for sampling)
# sample_table = np.array(list(itertools.chain.from_iterable(sample_table)))

100%|█████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 400000/400000 [00:00<00:00, 1576835.65it/s]


In [ ]:
ls = [[124]*np.random for i in tqdm(range(int(1e8)))]
len(ls)

100%|███████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 100000000/100000000 [00:58<00:00, 1696849.76it/s]


100000000

In [5]:
print(torch.__version__) # Get PyTorch and CUDA version
print(f"{torch.cuda.is_available() = }") # Check that CUDA works
print(f"{torch.cuda.device_count() = }") # Check how many CUDA capable devices you have
# Print device human readable names
print(f"{torch.cuda.get_device_name(1) = }")

2.0.1
torch.cuda.is_available() = True
torch.cuda.device_count() = 7
torch.cuda.get_device_name(1) = 'NVIDIA GeForce RTX 2080 Ti'


In [18]:
from torchsummary  import summary

ModuleNotFoundError: No module named 'torchsummary'

In [12]:
class ModuleTest(nn.Module):
    def __init__(self):
        super().__init__()
        self.linear_layers = nn.ModuleList([nn.Linear(10, 10) for i in  range(10)])

    def forward(self, x):

        for i, l in enumerate(self.linears):
            x = self.linears[i//2](x) + l(x)
        return x

ModuleTest()
    

ModuleTest(
  (linear_layers): ModuleList(
    (0-9): 10 x Linear(in_features=10, out_features=10, bias=True)
  )
)

In [16]:
print(ModuleTest)

<class '__main__.ModuleTest'>
