In [1]:
import torch
from torch import nn

/mnt/efs/fs1/miniconda3/envs/gml/lib/python3.8/site-packages/tqdm/auto.py:22: TqdmWarning: IProgress not found. Please update jupyter and ipywidgets. See https://ipywidgets.readthedocs.io/en/stable/user_install.html
  from .autonotebook import tqdm as notebook_tqdm


In [42]:
import itertools
from collections import Counter

In [36]:
import numpy as np

In [12]:
emb_size = 1000
emb_dim = 10
embedding = nn.Embedding(emb_size, emb_dim)
sig = nn.Sigmoid()

In [28]:
emb_1 = embedding(torch.tensor([12, 2]))
emb_2 = embedding(torch.tensor([43, 32]))

In [29]:
emb_1

tensor([[ 0.7976,  0.5950, -1.2008,  0.1782, -0.1646, -0.3091,  1.3601, -1.1299,
         -1.8383,  0.3505],
        [ 0.0983,  0.6216,  1.2589,  1.7158,  0.7322, -0.0544, -1.1300,  0.7759,
         -0.3346, -1.5656]], grad_fn=<EmbeddingBackward0>)

In [30]:
emb_2

tensor([[ 1.2093e+00,  1.7658e+00, -1.5136e-01,  5.7025e-01, -6.0432e-01,
          1.0720e+00, -1.3632e+00,  4.4260e-01, -1.0252e+00,  3.1624e-01],
        [ 1.0852e+00,  3.6491e-01,  3.6029e-01,  3.2068e-01, -1.6258e+00,
          9.2224e-01, -2.0003e-01,  6.4078e-01,  9.4780e-04, -8.4548e-01]],
       grad_fn=<EmbeddingBackward0>)

In [39]:
torch.sum(emb_1*emb_2, dim = 1, dtype = torch.float)

tensor([1.7082, 2.1433], grad_fn=<SumBackward1>)

In [31]:
emb_1*emb_2

tensor([[ 9.6455e-01,  1.0507e+00,  1.8176e-01,  1.0163e-01,  9.9473e-02,
         -3.3134e-01, -1.8540e+00, -5.0009e-01,  1.8847e+00,  1.1083e-01],
        [ 1.0666e-01,  2.2683e-01,  4.5356e-01,  5.5023e-01, -1.1903e+00,
         -5.0173e-02,  2.2602e-01,  4.9715e-01, -3.1715e-04,  1.3237e+00]],
       grad_fn=<MulBackward0>)

In [37]:
np.sum([ 9.6455e-01,  1.0507e+00,  1.8176e-01,  1.0163e-01,  9.9473e-02,
         -3.3134e-01, -1.8540e+00, -5.0009e-01,  1.8847e+00,  1.1083e-01])

1.7082129999999998

In [45]:
list(itertools.chain.from_iterable([[1,1,1], [21,5,7,8]]))

[1, 1, 1, 21, 5, 7, 8]

In [43]:
Counter([1,1,1,1,1,3,4,23,4,2,4,2,4,5,6,6,6,6,6])

Counter({1: 5, 3: 1, 4: 4, 23: 1, 2: 2, 5: 1, 6: 5})